name: "Bug Report"
description: "Report a bug or regression."
labels:
    - bug
assignees: []
body:
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: Briefly describe the problem.
          placeholder: "What went wrong?"
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: Steps to Reproduce
          description: Provide clear steps to reproduce.
          placeholder: |
              1. Go to ...
              2. Click ...
              3. See error ...
      validations:
          required: true

    - type: input
      id: expected
      attributes:
          label: Expected Result
          placeholder: "What should have happened?"
      validations:
          required: true

    - type: input
      id: actual
      attributes:
          label: Actual Result
          placeholder: "What actually happened?"
      validations:
          required: true

    - type: dropdown
      id: severity
      attributes:
          label: Severity
          options:
              - Critical
              - Major
              - Minor
              - Trivial
      validations:
          required: false

    - type: textarea
      id: env
      attributes:
          label: Environment
          description: App version, browser/OS, device, feature flag, etc.
          placeholder: |
              - Version: v1.2.3
              - Browser/OS: Chrome 129, Windows 11
              - Env: Prod/Staging/Local
      validations:
          required: false

    - type: textarea
      id: evidence
      attributes:
          label: Logs / Screenshots
          description: Paste logs or attach screenshots.
          placeholder: "Attach images or code blocks with logs."
      validations:
          required: false

    - type: checkboxes
      id: regression
      attributes:
          label: Is this a regression?
          options:
              - label: Yes, it worked before
      validations:
          required: false

    - type: input
      id: story_points
      attributes:
          label: Estimate (Story Points)
          description: Rough effort estimate for planning.
          placeholder: "3"
      validations:
          required: false

    - type: input
      id: related
      attributes:
          label: Related Issues
          placeholder: "#123, #456"
      validations:
          required: false
